- name: Demo on variables
  hosts: localhost
  connection: local
  vars:
    URL: vars.google.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL - {{ URL }}

# Here in the above line, we have the value starting with a string URL, But if a value staring with a variable then we need quote it
     # msg: "{{ URL }}" , must and should double quote if the value starts with variable in ansible

- name: Demo on variables - from task
  hosts: localhost
  connection: local
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL - {{ URL }}
      vars:
        URL: tasks.google.com

- name: Demo on variables - Role variables
  hosts: localhost 
  connection: local
  roles:
    - sample  

## NOTE:- Precedence
    #1. CLI
    #2. Tasks
    #3. Roles- vars
    #4. playbook - play vars
    #5. Roles - defaults

 # -  name: Demo on register Variables
  #  hosts: local host
   # connection: local
    # become: yes
    #tasks:
     # - name: Check package 
      #  ansible.builtin.dnf:
       #     name: zlib
        #    state: installed



- name: Demo on register variables
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Check package
      ansible.builtin.dnf:
        name: zlib
        state: installed        
        


    
    



