- name: Demo on tags
  hosts: localhost
  connection: local
  tasks:
    - name: Install nginx
      ansible.builtin.debug:
        msg: Installed Nginx
      tags:
        - install
        
    - name: Start nginx
      ansible.builtin.debug:
        msg: Started Nginx
      tags: 
        - service      