- name: Error Handling
  hosts: localhost
  connection: local
  tasks:
    - name: Fail this command
      ansible.builtin.shell: exit 1


    - name: Print Hello
      ansible.builtin.debug:
        msg: Hello  