- name: Handlers
  hosts: localhost
  connection: local
  tasks:
    - name: install zlib
      ansible.builtin.dnf: ls

handlers:
  - name: Say Hello
    ansible.builtin.debug:
      msg: Hello , I am notified      
       