- name: Get vault credentials
  hosts: localhost
  connection: local
  tasks:
   - name: print password
     ansible.builtin.debug:
       msg: "{{ lookup('hashi_vault', 'test/data/my_credentials:password token={{ vault_token}} url=http://172.31.40.195:8200 validate_certs=false' )}}"